name: Build Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-gradle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Check Gradle Wrapper
        run: |
          chmod +x ./gradlew

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
    
      - name: Write API key and base URL to local.properties
        run: |
          echo "apikey=${{ secrets.apikey }}" > local.properties
          echo "baseurl=${{ secrets.baseurl }}" >> local.properties

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '7.3.2'

      - name: Run build with Gradle Wrapper
        run: ./gradlew build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with: 
            name: build-artifacts
            path: /home/runner/work/Drizzl/Drizzl/remote/build/generated/source/buildConfig/debug/com/jerry/sources/remote/



      - name: Run tests with Gradle Wrapper
        run: ./gradlew check
